# Generated by Django 4.1.9 on 2023-05-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=int, max_length=510),
            preserve_default=False,
        ),
    ]
